### ISSUE TITLE
ICL question

### ISSUE THREAD

**Issue by annamykcode** [HazyResearch/hyena-dna#12]
Hi! Thanks for the great work!
I'm currently investigating your ICL solutions (soft tokens and instruction tuning) and can't understand what actually "shots" means and what is it for. Can you please add more details?
Thanks

**Comment by exnx** [comment]
Thanks!

Shots refers to the number of samples (DNA sequences and their label) we "pack" into the context.  eg, 2 shots means packing 2 DNA sequences for each class in the dataset to show the model examples of what sequences and their corresponding label.  Checkout the paper appendix section A.3 for more details on this.
