### ISSUE TITLE
pretrain model weights miss pos_emb 

### ISSUE THREAD

**Issue by WalkerSue** [HazyResearch/hyena-dna#17]
Hi,exnx

I'm sorry to bother you. I want to use the pre-trained model weights you provided to fine-tune for downstream tasks. I found that some model parameters are missing. Is there anything wrong with my approach?

Some refactoring of the model parameter names was done using the code you provided before loading the model weights

Here is a more detailed translation:

####
pretrained_model_name = 'hyenadna-small-32k-seqlen'

max_lengths = {
    'hyenadna-tiny-1k-seqlen': 1024,
    'hyenadna-small-32k-seqlen': 32768,
    'hyenadna-medium-160k-seqlen': 160000,
    'hyenadna-medium-450k-seqlen': 450000,  # T4 up to here
    'hyenadna-large-1m-seqlen': 1_000_000,  # only A100 (paid tier)
}

max_length = max_lengths[pretrained_model_name]  # auto selects

%# data settings:
use_padding = True
rc_aug = False  # reverse complement augmentation
add_eos = False  # add end of sentence token

%# we need these for the decoder head, if using
use_head = True
n_classes = 1  # not used for embeddings only

%# you can override with your own backbone config here if you want,
%# otherwise we'll load the HF one in None
backbone_cfg = json.load(open(f'hungging_face_models/hyenadna/{pretrained_model_name}/config.json', 'r'))

model = hyenadna.HyenaDNAModel(**backbone_cfg, use_head=use_head, n_classes=n_classes)
pretrain_w = torch.load(f'hungging_face_models/hyenadna/{pretrained_model_name}/pytorch_model.bin')

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[12], line 1
----> 1 model.load_state_dict(pretrain_w)

File /Data/luokai/biotools/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1667, in Module.load_state_dict(self, state_dict, strict)
   1662         error_msgs.insert(
   1663             0, 'Missing key(s) in state_dict: {}. '.format(
   1664                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1666 if len(error_msgs) > 0:
-> 1667     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1668                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1669 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for HyenaDNAModel:
	Missing key(s) in state_dict: "backbone.layers.0.mixer.filter_fn.pos_emb.z", "backbone.layers.0.mixer.filter_fn.pos_emb.t", "backbone.layers.0.mixer.filter_fn.implicit_filter.3.freq", "backbone.layers.0.mixer.filter_fn.implicit_filter.5.freq", "backbone.layers.0.mixer.filter_fn.modulation.deltas", "backbone.layers.1.mixer.filter_fn.pos_emb.z", "backbone.layers.1.mixer.filter_fn.pos_emb.t", "backbone.layers.1.mixer.filter_fn.implicit_filter.3.freq", "backbone.layers.1.mixer.filter_fn.implicit_filter.5.freq", "backbone.layers.1.mixer.filter_fn.modulation.deltas", "backbone.layers.2.mixer.filter_fn.pos_emb.z", "backbone.layers.2.mixer.filter_fn.pos_emb.t", "backbone.layers.2.mixer.filter_fn.implicit_filter.3.freq", "backbone.layers.2.mixer.filter_fn.implicit_filter.5.freq", "backbone.layers.2.mixer.filter_fn.modulation.deltas", "backbone.layers.3.mixer.filter_fn.pos_emb.z", "backbone.layers.3.mixer.filter_fn.pos_emb.t", "backbone.layers.3.mixer.filter_fn.implicit_filter.3.freq", "backbone.layers.3.mixer.filter_fn.implicit_filter.5.freq", "backbone.layers.3.mixer.filter_fn.modulation.deltas", "head.output_transform.weight", "head.output_transform.bias".

Thanks,

**Comment by exnx** [comment]
can you describe more? eg, which codebase are you using, colab, standalone_hyena, or main Pytorch Lightning?

At first glance, it may be similar to the issue described [here](https://github.com/HazyResearch/hyena-dna#model-config).

**Comment by exnx** [comment]
Also, in your title, you mention pos_emb, but don't describe the issue in the body.  For HyenaDNA, we do not use positional embeddings for the tokens.  It uses a convolution, which has a sense of position already and so no need for pos_emb.

We do use positional embeddings differently in the filter function to create the implicit convolution kernel.  Is that what you were referring to?  Those are not learned and so do not have parameters.

**Comment by WalkerSue** [comment]
Thanks for the reply @exnx, I use "standalone_hyena"。 It's should be positional embeddings of  implicit convolution kernel which you mentioned. Thanks again,Great work!  I'll review the model structure or try the Pytorch Lightning version training code you provided

**Comment by exnx** [comment]
Sure thing.  I recommend using the colab example to work through the [colab](https://colab.research.google.com/drive/1wyVEQd4R3HYLTUOXEEQmp_I8aNC_aLhL?usp=sharing).  Once that works then try the other training code.

**Comment by exnx** [comment]
Did you figure it out?

**Comment by WalkerSue** [comment]
> Did you figure it out?

Sorry for the delayed response to your information. The issue has been resolved, It's due to not inject   "mixer.layer" during the loading process, which resulted in the missing of these weights.

Currently, the performance indicators of Hyenadna model are comparable to those of DNAbert in my task; however, given the short sequence length of this particular task, it may not fully reflect its advantages. Thank you for your exceptional work and assistance.

**Comment by WalkerSue** [comment]
need inject "mixer.layer"
