### ISSUE TITLE
Nucleotide vs codons

### ISSUE THREAD

**Issue by KadirErturk4r** [HazyResearch/hyena-dna#18]
Have you ever consider to use codons instead of single nucleotide prediction.
I mean convert sequence to codon code, train and try to predict next codon?

**Comment by KadirErturk4r** [comment]
it may be more make sense, since there are only 22 amino acid in proteins and 20 of them in universal genetic code. 
Like alphabet letters vs words. 
Also codon series may make regions more visible. (Think it as a words in a sentence)

if you have a new sequence are you able to make it chemically?

**Comment by exnx** [comment]
We certainly encourage folks to experiment with the model for their use cases.  As mentioned above, we're interested in regulatory regions too, which do not have a codon vocab.
