### ISSUE TITLE
ImportError: Error loading 'src.models.sequence.dna_embedding.DNAEmbeddingModel':

### ISSUE THREAD

**Issue by richardsun-voyager** [HazyResearch/hyena-dna#26]
When running the code as instructed (quick entry "python -m train wandb=null experiment=hg38/genomic_benchmark_scratch"), there was an error: "ImportError: Error loading 'src.models.sequence.dna_embedding.DNAEmbeddingModel':". Can you please look into it? Thanks!

**Comment by exnx** [comment]
Can you describe more details of your setup and steps?  What you described can be from many things.  eg, what environments and versions are you using?  If all else fails, try the Docker image.

**Comment by richardsun-voyager** [comment]
Hi. The issue has been solved, after the re-installation of flash-attention. Thanks!
