### ISSUE TITLE
Pre-trained model for genomic benchmarks

### ISSUE THREAD

**Issue by alancleary** [HazyResearch/hyena-dna#27]
Hello. We've been working through replicating the results from your arXiv paper to better understand HyenaDNA and how we can use it for our own purposes. Using the hyena-dna-nt6 Docker image, we were able to successfully replicate the "Nucleotide Transformer" experiments. However, we've been unable to replicate the "Genomic Benchmark" experiments because the `pretrained_model_path` in the `configs/experiment/hg38/genomic_benchmark.yaml` file is set to a path that doesn't exist in the container: `/local-scratch/nigam/projects/mwornow/projects/safari-internal/outputs/2023-04-14/2_128_1024.ckpt`.

Is this file available somewhere that we can access it? This appears to be the file that's generated by the [Quick Entry point]() experiment, but we would like to use a pre-trained model if possible before generating our own for this first round of validation.

Thanks!

**Comment by exnx** [comment]
Sure, checkout the [public weights](https://github.com/HazyResearch/hyena-dna#hugging-face-pretrained-weights) here.  It's the tiny-1k model.

**Comment by alancleary** [comment]
Thanks for the quick response @exnx. I had a suspicion we could use the pre-trained models on Hugging Face but didn't want to assume. Cheers!
