### ISSUE TITLE
Addition to Transformers

### ISSUE THREAD

**Issue by tanaymeh** [HazyResearch/hyena-dna#3]
First of all, excellent work! This model holds so much promise!

Is this model already in hugging face transformers? If not, I would like to volunteer in adding this model to Hugging face Transformers framework so it can be used by researchers easily.

Thanks!

**Comment by exnx** [comment]
Hi heytanay, it’s not already there, and that would be amazing if you wanted to add it! We’re definitely up for supporting where we can, clarification, pointers, sharp bits if you need. Thanks so so much!!!

**Comment by heytanay** [comment]
Thanks for the reply @exnx, I opened an Issue and will be opening a PR soon. Let's make this work!

https://github.com/huggingface/transformers/issues/24659

**Comment by exnx** [comment]
Closing this due to stale issue + someone from Huggingface is actively working porting over HyenaDNA to their library!
