### ISSUE TITLE
Trouble reproducing Genomics Benchmark Result

### ISSUE THREAD

**Issue by yair-schiff** [HazyResearch/hyena-dna#37]
Hello,

Thank you for the great work and repo!

I am trying to reproduce the HyenaDNA column of Table 4.1 (GenomicsBenchmark). I am using the weights from [`LongSafari/hyenadna-tiny-1k-seqlen`](https://huggingface.co/LongSafari/hyenadna-tiny-1k-seqlen). However, I am unable to reproduce the results.

Would it be possible for you to specify which hyperparms from Table A.3 (screenshot below) were used for each of the datasets in this benchmark:
<img width="647" alt="Screenshot 2023-12-19 at 10 49 24 PM" src="https://github.com/HazyResearch/hyena-dna/assets/35781889/eaddc028-abd8-4d1c-8dfd-91c567a348bc">

**Comment by exnx** [comment]
Sorry we don't have those readily available.

**Comment by yair-schiff** [comment]
Thanks for the reply!
