### ISSUE TITLE
Trouble reproducing Nucleotide Transformer Benchmarks Result

### ISSUE THREAD

**Issue by yair-schiff** [HazyResearch/hyena-dna#38]
Similar question to #37 :)

I am using [`LongSafari/hyenadna-tiny-1k-seqlen-d256`](https://huggingface.co/LongSafari/hyenadna-tiny-1k-seqlen-d256) and trying to reproduce the results from Table 4.2 (Nucleotide Transformer Benchmarks).

Are you able to specify which hyperparams from Table A.5 were used to get the best results for each NT task for HyenaDNA (1.6 M)
<img width="647" alt="Screenshot 2023-12-20 at 12 46 12 AM" src="https://github.com/HazyResearch/hyena-dna/assets/35781889/68fac579-1e99-4c80-90f8-457d93089205">

**Comment by exnx** [comment]
It's in the docker [image](https://github.com/HazyResearch/hyena-dna?tab=readme-ov-file#nucleotide-transformer-datasets).

**Comment by yair-schiff** [comment]
Thanks! Sorry I missed that in the README
