### ISSUE TITLE
Clarifying the models available on HF

### ISSUE THREAD

**Issue by yair-schiff** [HazyResearch/hyena-dna#39]
Hi,

On the [`LongSafari`](https://huggingface.co/LongSafari) HF space there appear to be 2 copies of each model, one with `-hf` at the end of the name and one without.

I was wondering what the difference is between these models (other than one being compatible with `AutoModel`), because despite the names being the same and the variables in the config files looking almost identical (i.e., same `d_model` and `n_layers`), they have very different number of parameters. For example,
- [`LongSafari/hyenadna-medium-160k-seqlen`](https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen) has `6.6M` parameters
- [`LongSafari/hyenadna-medium-160k-seqlen-hf`](https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf) has `12.9M` parameters

Which version of these models corresponds to the ones used in the paper experiments? If I am not mistaken, it should be the first one (i.e., the one **without** `-hf` in the name)?

**Comment by yair-schiff** [comment]
@exnx, after digging into the two versions of each model, it appears that the main difference is in how the `PositionalEmbedding` modules are defined:

That is, in the repo [here](https://github.com/HazyResearch/hyena-dna/blob/d553021b483b82980aa4b868b37ec2d4332e198a/src/models/sequence/hyena.py#L109-L131), the `PositionalEmbedding` model, has **no** learnable parameters: 
```
        self.register("z", z, lr=lr_pos_emb)
```

because in the config files(i.e., in [configs/experiment/hg38/hg38_hyena.yaml](https://github.com/HazyResearch/hyena-dna/blob/d553021b483b82980aa4b868b37ec2d4332e198a/configs/experiment/hg38/hg38_hyena.yaml#L30C7-L30C7)), `lr_pos_emb = 0.0`, so the code uses `register_buffer` (i.e., [here](https://github.com/HazyResearch/hyena-dna/blob/d553021b483b82980aa4b868b37ec2d4332e198a/src/utils/train.py#L148-L149))

However, on HF, the version of each model that has `-hf` in the name uses [this modeling code](https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/blob/ea0088449336057ea86be9e8de4f35775f620f46/modeling_hyena.py#L47-L70):
```
    self.z = nn.Parameter(z, requires_grad=True)
```

This increases the number of parameters for the `-hf` version of each model, especially for long sequence models.

------

So I guess my question is which of these would be the "correct" model to compare to and which was used in the paper's experiments?

**Comment by Rocketknight1** [comment]
Hi @yair-schiff, I think the version in this repo is more authoritative. This was an error in the HF port - I'll submit a fix soon, and hopefully the two versions should be equivalent after that!

**Comment by yair-schiff** [comment]
@Rocketknight1, thanks for following up. I should have posted here as well after I did some digging. The two models have equivalent weights. As you mention, I think it was just a small discrepancy in the HF port that set the `z` parameter to "learnable". Thanks!

**Comment by Rocketknight1** [comment]
@yair-schiff No probs! The code for the `-hf` models should now be updated with `z` as a buffer instead of a parameter.
