### ISSUE TITLE
ImportError: dropout_add_layer_norm is not installed

### ISSUE THREAD

**Issue by kunjiefan** [HazyResearch/hyena-dna#5]
Hi,

Great work! When I was trying to run `python -m train wandb=null experiment=hg38/genomic_benchmark_scratch`, I encountered the following error:

> Error executing job with overrides: ['wandb=null', 'experiment=hg38/genomic_benchmark_scratch']
> Traceback (most recent call last):
>   File "/home/fankunjie/toxic_gene/hyena-dna/train.py", line 691, in main
>     train(config)
>   File "/home/fankunjie/toxic_gene/hyena-dna/train.py", line 653, in train
>     model = SequenceLightningModule(config)
>   File "/home/fankunjie/toxic_gene/hyena-dna/train.py", line 148, in __init__
>     self.setup()  ## Added by KS
>   File "/home/fankunjie/toxic_gene/hyena-dna/train.py", line 172, in setup
>     self.model = utils.instantiate(registry.model, self.hparams.model)
>   File "/home/fankunjie/toxic_gene/hyena-dna/src/utils/config.py", line 104, in instantiate
>     return obj()
>   File "/home/fankunjie/toxic_gene/hyena-dna/src/models/sequence/dna_embedding.py", line 36, in __init__
>     self.backbone = LMBackbone(
>   File "/home/fankunjie/toxic_gene/hyena-dna/src/models/sequence/long_conv_lm.py", line 305, in __init__
>     raise ImportError("dropout_add_layer_norm is not installed")
> ImportError: dropout_add_layer_norm is not installed

I followed exactly the same steps mentioned in the Readme, except the installation of flash attention. I had trouble installing flash attention, and successfully installed it using `pip install flash-attn --no-build-isolation` following this post: https://github.com/HazyResearch/flash-attention/issues/246.

Thanks for your help!

**Comment by exnx** [comment]
Thanks!  Good catch.

Pass in the flag with `model.fused_dropout_add_ln=False` in the command line, or set that value to `False` in the config itself.  Otherwise, you'll need to install that package (below).

```
# from inside flash-attn/
cd csrc/layer_norm && pip install .
```

**Comment by kunjiefan** [comment]
Thanks for your quick reply! It solves the problem perfectly.

**Comment by jimmylihui** [comment]
> Thanks! Good catch.
> 
> Pass in the flag with `model.fused_dropout_add_ln=False` in the command line, or set that value to `False` in the config itself. Otherwise, you'll need to install that package (below).
> 
> ```
> # from inside flash-attn/
> cd csrc/layer_norm && pip install .
> ```

Hi Did you feel the installation is very slow?

**Comment by DylanMannKrzisnik** [comment]
> > Thanks! Good catch.
> > Pass in the flag with `model.fused_dropout_add_ln=False` in the command line, or set that value to `False` in the config itself. Otherwise, you'll need to install that package (below).
> > ```
> > # from inside flash-attn/
> > cd csrc/layer_norm && pip install .
> > ```
> 
> Hi Did you feel the installation is very slow?

Indeed, is there a faster alternative for installing from csrc/layer_norm ?
