### ISSUE TITLE
Thank you for doing this, and thank you for open-sourcing it!

### ISSUE THREAD

**Issue by Tylersuard** [HazyResearch/hyena-dna#8]
Thank you for creating this repo.  I have been working on this problem for around 6 months, without much success on my end.  Thank you for doing all this!  This is a historic achievement.

**Comment by exnx** [comment]
Wow thank you for the encouragement! And we're *so* glad you find the work interesting.  We're especially excited to hear how you might use it and if it actually works for you.  We always want to iterate :)

**Comment by dbrami** [comment]
I second @Tylersuard sincere congrats and thanks. I read your blog post on Saturday and haven't stopped thinking about it!
